planning_pipelines:
  default_planning_pipeline: pilz_industrial_motion_planner
  pipeline_names:
    - pilz_industrial_motion_planner

pilz_industrial_motion_planner:
  planning_plugin: pilz_industrial_motion_planner/CommandPlanner
  request_adapters: ""
  start_state_max_bounds_error: 0.1
